kind: pipeline
type: docker
name: default

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}.git
      - cd ${DRONE_REPO_NAME}

  - name: test
    image: node:16
    commands:
      - npm install
      - npm test

  - name: build
    image: node:16
    commands:
      - npm run build

  - name: docker_build
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
      tags: latest

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
